{% set name = "xarray_selafin" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dc4a78dc251dc20d6fd6616104a376b3281c111d800529784eedc2d062ef795

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9
    - numpy
    - xarray

test:
  imports:
    - xarray_selafin
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/seareport/xarray-selafin.git
  summary: 'xarray backend for Selafin formats'
  license: Unlicense
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tomsail
    - pmav99
