{% set name = "xarray_selafin" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e0966364047a252e920dfcce1cdf0eb1311a6349d434579ba7f455a3debd8ba

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9
    - numpy
    - xarray

test:
  imports:
    - xarray_selafin
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/seareport/xarray-selafin.git
  summary: 'xarray backend for Selafin formats'
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tomsail
    - pmav99
